name: Docker Image CI

on:
  release: 
    types: 
    - created
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
          VERSION=$(data +%s)
          docker build . --file Dockerfile --tag stocks:${VERSION}
          docker login docker.pkg.github.com -u pash-slack --password ${{ secrets.GITHUB_TOKEN }} 
          docker tag stocks:${VERSION} docker.pkg.github.com/pash-slack/stocks_actions/stocks:${VERSION}
          docker push docker.pkg.github.com/pash-slack/stocks_actions/stocks:${VERSION}
